import * as FileSystem from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import QRCode from 'qrcode';

function escapeHtml(value = '') {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function buildNutritionRows(nutrition = {}) {
  const entries = [
    ['Energy', `${nutrition.energy || 0} kcal`],
    ['Protein', `${nutrition.protein || 0} g`],
    ['Carbs', `${nutrition.carbs || 0} g`],
    ['Sugar', `${nutrition.sugar || 0} g`],
    ['Fat', `${nutrition.fat || 0} g`],
    ['Saturated Fat', `${nutrition.saturatedFat || 0} g`],
    ['Fiber', `${nutrition.fiber || 0} g`],
    ['Sodium', `${nutrition.sodium || 0} mg`],
  ];

  return entries
    .map(([label, value]) => `
      <tr>
        <td style="padding: 8px 0; border-bottom: 1px solid #E5E7EB; color: #475569;">${escapeHtml(label)}</td>
        <td style="padding: 8px 0; border-bottom: 1px solid #E5E7EB; text-align: right; font-weight: 600; color: #111827;">${escapeHtml(value)}</td>
      </tr>
    `)
    .join('');
}

function buildIngredientsMarkup(ingredients = []) {
  const list = Array.isArray(ingredients) ? ingredients.filter(Boolean) : [];
  if (!list.length) {
    return '<p style="margin: 0; color: #64748B;">No ingredients listed.</p>';
  }

  return `
    <ul style="margin: 0; padding-left: 18px; color: #111827; line-height: 1.6;">
      ${list.map((ingredient) => `<li>${escapeHtml(ingredient)}</li>`).join('')}
    </ul>
  `;
}

export async function generateQrPdf(product) {
  if (!product?.ffadzCode) {
    return { success: false, error: 'Missing FFADZ code for PDF generation.' };
  }

  try {
    const qrSvgString = await QRCode.toString(product.ffadzCode, {
      type: 'svg',
      margin: 1,
      width: 240,
      color: {
        dark: '#111827',
        light: '#FFFFFF',
      },
    });

    const html = `
      <html>
        <body style="font-family: Arial, sans-serif; padding: 28px; color: #111827;">
          <div style="max-width: 720px; margin: 0 auto;">
            <div style="text-align: center; margin-bottom: 24px;">
              <div style="display: inline-block; padding: 6px 12px; border-radius: 999px; background: #DBEAFE; color: #1D4ED8; font-size: 12px; font-weight: 700;">
                ${escapeHtml(product.ffadzCode)}
              </div>
              <h1 style="margin: 16px 0 8px 0; font-size: 28px;">${escapeHtml(product.name || 'Untitled Product')}</h1>
              <p style="margin: 0; color: #475569; font-size: 14px;">
                ${escapeHtml(product.brand || 'Personal FFADZ product')}
              </p>
            </div>

            <div style="display: flex; justify-content: center; margin-bottom: 24px;">
              <div style="border: 1px solid #E5E7EB; border-radius: 24px; padding: 18px; background: #FFFFFF; text-align: center;">
                ${qrSvgString}
              </div>
            </div>

            <div style="display: grid; grid-template-columns: 1fr; gap: 20px;">
              <section style="border: 1px solid #E5E7EB; border-radius: 18px; padding: 18px;">
                <h2 style="margin: 0 0 12px 0; font-size: 20px;">Ingredients</h2>
                ${buildIngredientsMarkup(product.ingredients)}
              </section>

              <section style="border: 1px solid #E5E7EB; border-radius: 18px; padding: 18px;">
                <h2 style="margin: 0 0 12px 0; font-size: 20px;">Nutrition (per 100g)</h2>
                <table style="width: 100%; border-collapse: collapse;">
                  ${buildNutritionRows(product.nutrition)}
                </table>
              </section>
            </div>

            <footer style="margin-top: 28px; padding-top: 16px; border-top: 1px solid #E5E7EB; text-align: center; color: #64748B; font-size: 12px;">
              Generated by Ffadz
            </footer>
          </div>
        </body>
      </html>
    `;

    const pdf = await Print.printToFileAsync({ html });
    const destination = `${FileSystem.documentDirectory || ''}${product.ffadzCode}.pdf`;

    if (pdf.uri !== destination) {
      await FileSystem.copyAsync({
        from: pdf.uri,
        to: destination,
      });
    }

    return {
      success: true,
      uri: destination,
      qrSvgString,
    };
  } catch (error) {
    return {
      success: false,
      error: error.message || 'Could not generate the QR PDF.',
    };
  }
}
