// Ffads — Supabase Service (Redirected to services/supabase/)
// This file re-exports from the new modular location for backward compatibility.
export {
  setSupabaseCredentials,
  getSupabaseClient,
  isConfigured,
  pingSupabase,
  saveProduct,
  saveProductAIData,
  getProducts,
  getProductByBarcode,
  getCompleteProduct,
  deleteProduct,
  getDeepIngredientKnowledge,
  updateDeepIngredientKnowledge,
  recordScan,
  getUserScanHistory,
  logUserContribution,
  getUserContributions,
  getContributionCount,
  saveUserProfile,
  getUserProfile,
  saveProductImage,
  getProductImages,
  createPersonalProduct,
  listPersonalProducts,
  getPersonalProductByCode,
  getPersonalProductById,
  lookupPersonalQr,
  recordPersonalProductScan,
} from './supabase/index';
